CREATE TABLE IF NOT EXISTS `reimbursement_claim` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `reimbursement_no` varchar(64) NULL DEFAULT NULL COMMENT '报销单号',
  `user_id` bigint NOT NULL COMMENT '申请人用户编号',
  `dept_id` bigint NULL DEFAULT NULL COMMENT '申请人部门编号快照',
  `applicant_name_snapshot` varchar(64) NOT NULL DEFAULT '' COMMENT '申请人名称快照',
  `reason` varchar(512) NOT NULL DEFAULT '' COMMENT '报销事由',
  `total_amount` decimal(24, 6) NOT NULL DEFAULT 0 COMMENT '报销总金额',
  `currency` varchar(8) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `status` tinyint NOT NULL COMMENT '报销业务状态',
  `process_instance_id` varchar(64) NULL DEFAULT NULL COMMENT 'BPM 流程实例编号',
  `source` varchar(16) NOT NULL DEFAULT 'MANUAL' COMMENT '来源',
  `mailbox_connection_id` bigint NULL DEFAULT NULL COMMENT '来源邮箱绑定编号',
  `ai_confidence` decimal(5, 4) NULL DEFAULT NULL COMMENT 'AI 总体置信度',
  `ai_failure_message` varchar(512) NULL DEFAULT NULL COMMENT 'AI 失败原因',
  `submit_time` datetime NULL DEFAULT NULL COMMENT '提交时间',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_reimbursement_claim_no` (`tenant_id`, `reimbursement_no`) USING BTREE,
  KEY `idx_reimbursement_claim_user` (`tenant_id`, `user_id`, `status`) USING BTREE,
  KEY `idx_reimbursement_claim_process` (`process_instance_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报销申请';

CREATE TABLE IF NOT EXISTS `reimbursement_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `reimbursement_id` bigint NOT NULL COMMENT '报销编号',
  `client_item_id` varchar(64) NOT NULL COMMENT '请求内明细编号',
  `expense_date` date NOT NULL COMMENT '费用日期',
  `expense_type` varchar(32) NOT NULL COMMENT '费用类型',
  `merchant_name` varchar(128) NULL DEFAULT NULL COMMENT '商户名称',
  `amount` decimal(24, 6) NOT NULL COMMENT '金额',
  `tax_amount` decimal(24, 6) NULL DEFAULT NULL COMMENT '税额',
  `invoice_number` varchar(128) NULL DEFAULT NULL COMMENT '发票号码',
  `remark` varchar(512) NULL DEFAULT NULL COMMENT '备注',
  `ai_confidence` decimal(5, 4) NULL DEFAULT NULL COMMENT 'AI 置信度',
  `manually_modified` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否人工修改',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_reimbursement_item_client` (`tenant_id`, `reimbursement_id`, `client_item_id`) USING BTREE,
  KEY `idx_reimbursement_item_claim` (`tenant_id`, `reimbursement_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报销明细';

CREATE TABLE IF NOT EXISTS `reimbursement_attachment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `reimbursement_id` bigint NOT NULL COMMENT '报销编号',
  `item_id` bigint NULL DEFAULT NULL COMMENT '关联明细编号',
  `external_artifact_id` varchar(128) NULL DEFAULT NULL COMMENT '邮件附件稳定编号',
  `file_url` varchar(1024) NOT NULL COMMENT '文件 URL',
  `file_name` varchar(255) NULL DEFAULT NULL COMMENT '文件名',
  `mime_type` varchar(128) NULL DEFAULT NULL COMMENT 'MIME 类型',
  `size` bigint NULL DEFAULT NULL COMMENT '文件大小',
  `sha256` varchar(64) NULL DEFAULT NULL COMMENT 'SHA-256',
  `document_type` varchar(32) NULL DEFAULT NULL COMMENT '单据类型',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_reimbursement_attachment_external` (`tenant_id`, `reimbursement_id`, `external_artifact_id`) USING BTREE,
  KEY `idx_reimbursement_attachment_claim` (`tenant_id`, `reimbursement_id`) USING BTREE,
  KEY `idx_reimbursement_attachment_item` (`item_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报销附件';

CREATE TABLE IF NOT EXISTS `reimbursement_mailbox_connection` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `owner_user_id` bigint NOT NULL COMMENT '所属用户编号',
  `provider_code` varchar(32) NOT NULL COMMENT '邮箱提供方',
  `email_normalized` varchar(255) NOT NULL COMMENT '规范化邮箱地址',
  `username` varchar(255) NOT NULL COMMENT 'IMAP 用户名',
  `imap_host` varchar(255) NOT NULL COMMENT 'IMAPS 主机',
  `imap_port` int NOT NULL COMMENT 'IMAPS 端口',
  `tls_verification` varchar(32) NOT NULL DEFAULT 'strict' COMMENT 'TLS 校验模式',
  `credential_ciphertext` varchar(2048) NOT NULL COMMENT '加密后的授权码',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '验证状态',
  `verified_at` datetime NULL DEFAULT NULL COMMENT '最近验证时间',
  `last_failure_message` varchar(255) NULL DEFAULT NULL COMMENT '最近失败原因',
  `creator` varchar(64) NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_reimbursement_mailbox_owner` (`tenant_id`, `owner_user_id`, `provider_code`, `email_normalized`, `deleted`) USING BTREE,
  KEY `idx_reimbursement_mailbox_owner_status` (`tenant_id`, `owner_user_id`, `status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户报销邮箱绑定';

-- 智能报销菜单：只插入页面菜单和按钮权限，不插入角色绑定。
INSERT INTO `system_menu` (`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`, `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES
(12510100, '智能报销', '', 2, 90, 1185, 'reimbursement', 'fa:money', 'reimbursement/index', 'ReimbursementClaim', 0, b'1', b'1', b'1', 'admin', '2026-07-20 00:00:00', 'admin', '2026-07-20 00:00:00', b'0'),
(12510101, '智能报销查询', 'reimbursement:claim:query', 3, 1, 12510100, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', '2026-07-20 00:00:00', 'admin', '2026-07-20 00:00:00', b'0'),
(12510102, '智能报销全部查询', 'reimbursement:claim:query-all', 3, 2, 12510100, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', '2026-07-20 00:00:00', 'admin', '2026-07-20 00:00:00', b'0'),
(12510103, '智能报销创建', 'reimbursement:claim:create', 3, 3, 12510100, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', '2026-07-20 00:00:00', 'admin', '2026-07-20 00:00:00', b'0'),
(12510104, '智能报销更新/确认', 'reimbursement:claim:update', 3, 4, 12510100, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', '2026-07-20 00:00:00', 'admin', '2026-07-20 00:00:00', b'0'),
(12510105, '智能报销提交', 'reimbursement:claim:submit', 3, 5, 12510100, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', '2026-07-20 00:00:00', 'admin', '2026-07-20 00:00:00', b'0'),
(12510106, '智能报销邮箱管理', 'reimbursement:mailbox:manage', 3, 6, 12510100, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', '2026-07-20 00:00:00', 'admin', '2026-07-20 00:00:00', b'0'),
(12510107, '智能报销邮箱导入', 'reimbursement:mail-import:start', 3, 7, 12510100, '', '', '', NULL, 0, b'1', b'1', b'1', 'admin', '2026-07-20 00:00:00', 'admin', '2026-07-20 00:00:00', b'0')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `permission` = VALUES(`permission`),
  `type` = VALUES(`type`),
  `sort` = VALUES(`sort`),
  `parent_id` = VALUES(`parent_id`),
  `path` = VALUES(`path`),
  `icon` = VALUES(`icon`),
  `component` = VALUES(`component`),
  `component_name` = VALUES(`component_name`),
  `status` = VALUES(`status`),
  `visible` = VALUES(`visible`),
  `keep_alive` = VALUES(`keep_alive`),
  `always_show` = VALUES(`always_show`),
  `deleted` = b'0';
